### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by remz1337** [GMUEClab/ecj#61]
Hello,

I just downloaded the latest release (v27) and ran `mvn clean package` but I'm getting multiple errors.

Using Java 1.8 and Maven 3 (from IntelliJ)

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ecj: There are test failures.`

Thanks

**Comment by remz1337** [comment]
I just tried on my linux machine and didn't work either.
`git clone ecj`
`mvn clean package`

and I get :
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project ecj`

**Comment by eclab** [comment]
I'd recently made a non-backward-compatible change to Evolve and forgot to change the tests accordingly.  I added a little bit of backward compatibleness again. See if it builds now.

**Comment by remz1337** [comment]
Thanks, it now builds successfully on Linux, but I still have some tests failure on Windows. I'll close this one and open another issue.

**Comment by SigmaX** [comment]
@eclab — the "fatal errors" do indeed appear fishy.  I'll try and look later this week and see if our test harness has false negatives.

**Comment by SigmaX** [comment]
I went ahead and silenced the output of the tests (commit https://github.com/GMUEClab/ecj/commit/b188e3578343eaf50ff83fff0ed5c3d1c662b7fd).  Some of the tests check for failures that are expected, so they do indeed print out "FATAL ERROR" upon success.  Not sure if silencing everything is the best idea long term (since it could make it harder to debug failing tests), but at least the output of success is unambiguous this way.
